index:
  path: /
  controller: App\Controller\LegendsGGController::index

tier:
  path: /tier
  controller: App\Controller\LegendsGGController::tier

ranking:
  path: /ranking
  controller: App\Controller\LegendsGGController::ranking

lol-esports:
  path: /lol-esports
  controller: App\Controller\LegendsGGController::lolEsports

tft-items:
  path: /tft/items
  controller: App\Controller\LegendsGGController::tftItems

tft-comps:
  path: /tft/comps
  controller: App\Controller\LegendsGGController::tftComps

tft-rank:
  path: /tft/ranking
  controller: App\Controller\LegendsGGController::tftRank

find-summoner:
  path: /summoner
  controller: App\Controller\LegendsGGController::findSummoner
  methods: ["POST"]

summoner:
  path: /summoner/{server}/{summoner}
  controller: App\Controller\LegendsGGController::summoner

error:
  path: /error/{error}
  controller: App\Controller\LegendsGGController::error

only-error:
  path: /error
  controller: App\Controller\LegendsGGController::onlyError