index:
  path: /
  controller: App\Controller\LegendsGGController::index

versus:
  path: /versus
  controller: App\Controller\LegendsGGController::versus

versus-find:
  path: /vs
  controller: App\Controller\LegendsGGController::versusFind
  methods: ["POST"]

versus-action:
  path: /versus/{server}/{summoner1}/{summoner2}
  controller: App\Controller\LegendsGGController::versusAction

ranking:
  path: /ranking
  controller: App\Controller\LegendsGGController::ranking

lol-esports:
  path: /lol-esports
  controller: App\Controller\LegendsGGController::lolEsports

tft-items:
  path: /tft/items
  controller: App\Controller\LegendsGGController::tftItems

tft-comps:
  path: /tft/comps
  controller: App\Controller\LegendsGGController::tftComps

tft-rank:
  path: /tft/ranking
  controller: App\Controller\LegendsGGController::tftRank

find-summoner:
  path: /summoner
  controller: App\Controller\LegendsGGController::findSummoner
  methods: ["POST"]

summoner:
  path: /summoner/{server}/{summoner}
  controller: App\Controller\LegendsGGController::summoner

error:
  path: /error/{error}
  controller: App\Controller\LegendsGGController::error

only-error:
  path: /error
  controller: App\Controller\LegendsGGController::onlyError

subscription:
  path: /subscription
  controller: App\Controller\SubscriptionController::subscription
  methods: ["POST"]

confirm-subscription:
  path: /confirm/{email}/{id}
  controller: App\Controller\SubscriptionController::confirmSubscription